// Generated by CoffeeScript 1.3.3
/*
An Actor is an object that exists in the Greenfoot world.
Every Actor has a location in the world, and an appearance (that is: an icon).

An Actor is not normally instantiated, but instead
used as a superclass to more specific objects in the world.
Every object that is intended to appear in the world must extend Actor.
Subclasses can then define their own appearance and behaviour.

One of the most important aspects of this class is the 'act' method.
This method is called when the 'Act' or 'Run' buttons
are activated in the Greenfoot interface.
The method here is empty, and subclasses normally
provide their own implementations.

<http://www.greenfoot.org/files/javadoc/greenfoot/Actor.html>
*/

var Actor;

Actor = (function() {

  function Actor() {}

  Actor.prototype.act = function() {};

  Actor.prototype.getImage = function() {
    return this.image;
  };

  Actor.prototype.getIntersectingObects = function() {};

  Actor.prototype.getNeighbour = function() {};

  Actor.prototype.getObjectsAtOffest = function() {};

  Actor.prototype.getObjectsInRange = function() {};

  Actor.prototype.getOneInterceptingObject = function() {};

  Actor.prototype.getRotation = function() {
    return this.rotation;
  };

  Actor.prototype.getWorld = function() {
    return this.world;
  };

  Actor.prototype.getX = function() {
    failIfNotInWorld();
    return this.x;
  };

  Actor.prototype.getY = function() {
    failIfNotInWorld();
    return this.y;
  };

  Actor.prototype.intersects = function() {};

  Actor.prototype.move = function(distance) {};

  Actor.prototype.setImage = function() {};

  Actor.prototype.setLocation = function(x, y) {};

  Actor.prototype.setRotation = function(rotation) {
    if (rotation >= 360) {
      if (rotation < 720) {
        rotation -= 360;
      } else {
        rotation %= 360;
      }
    } else if (rotation < 0) {
      if (rotation >= -360) {
        rotation += 360;
      } else {
        rotation = 360 + (rotation % 360);
      }
    }
    if (this.rotation !== rotation) {
      this.rotation = rotation;
      this.boundingRect = null;
      return sizeChanged();
    }
  };

  Actor.prototype.turn = function(amount) {
    return setRotation(this.rotation + amount);
  };

  Actor.prototype.turnTowards = function(x, y) {};

  return Actor;

})();

module.exports = Actor;
