// Generated by CoffeeScript 1.3.3

/*
An image to be shown on screen.
The image may be loaded from an image file and/or
drawn by using various drawing methods.

<http://www.greenfoot.org/files/javadoc/greenfoot/GreenfootImage.html>
*/


(function() {
  var GreenfootImage;

  GreenfootImage = (function() {

    function GreenfootImage() {}

    GreenfootImage.prototype.clear = function() {};

    GreenfootImage.prototype.drawImage = function() {};

    GreenfootImage.prototype.drawLine = function() {};

    GreenfootImage.prototype.drawOval = function() {};

    GreenfootImage.prototype.drawPolygon = function() {};

    GreenfootImage.prototype.drawRect = function() {};

    GreenfootImage.prototype.drawShape = function() {};

    GreenfootImage.prototype.drawString = function() {};

    GreenfootImage.prototype.fill = function() {};

    GreenfootImage.prototype.fillOval = function() {};

    GreenfootImage.prototype.fillPolygon = function() {};

    GreenfootImage.prototype.fillRect = function() {};

    GreenfootImage.prototype.fillShape = function() {};

    GreenfootImage.prototype.getAwtImage = function() {};

    GreenfootImage.prototype.getColor = function() {};

    GreenfootImage.prototype.getColorAt = function() {};

    GreenfootImage.prototype.getFont = function() {};

    GreenfootImage.prototype.getHeight = function() {};

    GreenfootImage.prototype.getTransparency = function() {};

    GreenfootImage.prototype.getWidth = function() {};

    GreenfootImage.prototype.mirrorHorizontally = function() {};

    GreenfootImage.prototype.mirrorVertically = function() {};

    GreenfootImage.prototype.rotate = function() {};

    GreenfootImage.prototype.scale = function() {};

    GreenfootImage.prototype.setColor = function() {};

    GreenfootImage.prototype.setColorAt = function() {};

    GreenfootImage.prototype.setFont = function() {};

    GreenfootImage.prototype.setTransparency = function() {};

    GreenfootImage.prototype.toString = function() {};

    return GreenfootImage;

  })();

  module.exports = GreenfootImage;

}).call(this);
