// Generated by CoffeeScript 1.3.3
/*
This utility class provides methods to control
the simulation and interact with the system.

<http://www.greenfoot.org/files/javadoc/greenfoot/Greenfoot.html>
*/

var Greenfoot;

Greenfoot = {
  constructor: function() {},
  delay: function() {},
  getKey: function() {},
  getMicLevel: function() {},
  getMouseInfo: function() {},
  getRandomNumber: function() {},
  isKeyDown: function() {},
  mouseClicked: function() {},
  mouseDragEnded: function() {},
  mouseDragged: function() {},
  mouseMoved: function() {},
  mousePressed: function() {},
  playSound: function() {},
  setSpeed: function() {},
  setWorld: function() {},
  start: function() {},
  stop: function() {}
};

module.exports = Greenfoot;
