// Generated by CoffeeScript 1.3.3
/*
Represents audio that can be played in Greenfoot.
A GreenfootSound loads the audio from a file.
The sound cannot be played several times simultaneously,
but can be played several times sequentially.
Most files of the following formats are supported:
AIFF, AU, WAV, MP3 and MIDI.

<http://www.greenfoot.org/files/javadoc/greenfoot/GreenfootSound.html>
*/

var GreenfootSound;

GreenfootSound = (function() {

  function GreenfootSound(filename) {
    this.filename = filename;
  }

  GreenfootSound.prototype.getVolume = function() {};

  GreenfootSound.prototype.isPlaying = function() {};

  GreenfootSound.prototype.pause = function() {};

  GreenfootSound.prototype.play = function() {};

  GreenfootSound.prototype.playLoop = function() {};

  GreenfootSound.prototype.setVolume = function() {};

  GreenfootSound.prototype.stop = function() {};

  GreenfootSound.prototype.toString = function() {};

  return GreenfootSound;

})();

module.exports = GreenfootSound;
