// Generated by CoffeeScript 1.3.3
/*
This class contains information about the current status of the mouse.
You can get a MouseInfo object via Greenfoot.getMouseInfo().

<http://www.greenfoot.org/files/javadoc/greenfoot/MouseInfo.html>
*/

var MouseInfo;

MouseInfo = (function() {

  function MouseInfo() {}

  MouseInfo.prototype.getActor = function() {};

  MouseInfo.prototype.getButton = function() {};

  MouseInfo.prototype.getClickCount = function() {};

  MouseInfo.prototype.getX = function() {};

  MouseInfo.prototype.getY = function() {};

  MouseInfo.prototype.toString = function() {};

  return MouseInfo;

})();

module.exports = MouseInfo;
