// Generated by CoffeeScript 1.3.3
/*
This class contains information about the current status of the mouse.
You can get a MouseInfo object via Greenfoot.getMouseInfo().

<http://www.greenfoot.org/files/javadoc/greenfoot/MouseInfo.html>
*/

var MouseInfo;

MouseInfo = (function() {

  function MouseInfo() {}

  MouseInfo.prototype.getActor = function() {
    return this.actor;
  };

  MouseInfo.prototype.getButton = function() {
    return this.button;
  };

  MouseInfo.prototype.getClickCount = function() {
    return this.clickCount;
  };

  MouseInfo.prototype.getX = function() {
    return this.x;
  };

  MouseInfo.prototype.getY = function() {
    return this.y;
  };

  MouseInfo.prototype.toString = function() {
    return "MouseInfo. Actor: " + actor + "  Location: (" + x + "," + y + ")  Button: " + button + " Click Count: " + clickCount;
  };

  return MouseInfo;

})();

module.exports = MouseInfo;
