// Generated by CoffeeScript 1.3.3
/*
World is the world that Actors live in.
It is a two-dimensional grid of cells.

All Actor are associated with a World
and can get access to the world object.
The size of cells can be specified at world creation time,
and is constant after creation.
Simple scenarios may use large cells
that entirely contain the representations of objects in a single cell.
More elaborate scenarios may use smaller cells (down to single pixel size)
to achieve fine-grained placement and smoother animation.

The world background can be decorated with drawings or images.

<http://www.greenfoot.org/files/javadoc/greenfoot/World.html>
*/

var World;

World = (function() {

  function World(worldWidth, worldheight, cellSize, bounded) {
    if (bounded == null) {
      bounded = true;
    }
    initialize(worldWidth(worldHeight(cellSize)));
    this.isBounded = bounded;
    this.backgroundIsClassImage = true;
  }

  World.prototype.act = function() {};

  World.prototype.addObject = function() {};

  World.prototype.getBackground = function() {};

  World.prototype.getCellSize = function() {
    return this.cellSize;
  };

  World.prototype.getColorAt = function() {};

  World.prototype.getHeight = function() {
    return this.height;
  };

  World.prototype.getObjects = function() {};

  World.prototype.getObjectsAt = function() {};

  World.prototype.getWidth = function() {
    return this.width;
  };

  World.prototype.numberOfObjects = function() {};

  World.prototype.removeObject = function() {};

  World.prototype.removeObjects = function() {};

  World.prototype.repaint = function() {};

  World.prototype.setActOrder = function() {};

  World.prototype.setBackground = function() {};

  World.prototype.setPaintOrder = function() {};

  World.prototype.started = function() {};

  World.prototype.stopped = function() {};

  return World;

})();

module.exports = World;
